-- TABELA STAGING - ROAMING INTERNACIONAL INBOUND
SET QUERY_BAND = 'name=INT_ROAMING;' FOR SESSION;
CREATE MULTISET TABLE U_INT_ATACADO.STG_RMNG_INT_INB(
	
	-- COLUNAS CARREGADAS DA DCH
	TAP_FILE_CURRENT_PROCESSING_DATE TIMESTAMP,
    DATE_CALL TIMESTAMP,
    PMN_SETTLEMENT_TADIG_CODE VARCHAR(8000),
    CALL_TYPE VARCHAR(8000),
    IMSI VARCHAR(8000),
    MSISDN VARCHAR(8000),
    APN_NETWORK VARCHAR(8000),
    DEVICE_TAC_CODE VARCHAR(8000),
    NUMBER_OF_CALLS INTEGER,
    CHARGED_SMS INTEGER,
    CHARGED_MINUTES NUMBER(15,5),
    CHARGED_MB NUMBER(15,5),
    SETTLEMENT_GROSS_CHARGE_USD NUMBER(15,5),
    
    -- COLUNAS PREENCHIDAS PELO LOADER
    DIRECTION CHAR(3),
    SOURCE_FILE_NAME VARCHAR(255), -- Arquivo de origem da informacao
  	SOURCE_SYSTEM VARCHAR(255), -- Sistema de Origem (DCH, BO, etc)
  	JOB_NAME VARCHAR(255), -- Job que realizou a carga
  	ETL_BATCH_ID VARCHAR(50), -- ID de Batch
  	
  	-- COLUNAS PREENCHIDAS AUTOMATICAMENTE
  	ROW_CREATE_TS TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP, -- TIMESTAMP em que a informacao foi carregada no Teradata
	ROW_CREATE_USER VARCHAR(128) DEFAULT USER -- Usuario que carregou a informacao
);

CREATE MULTISET TABLE U_INT_ATACADO.STG_RMNG_INT_OUT(
	-- COLUNAS CARREGADAS DA DCH
	TAP_FILE_CURRENT_PROCESSING_DATE TIMESTAMP,
    DATE_CALL TIMESTAMP,
    PMN_SETTLEMENT_TADIG_CODE VARCHAR(8000),
    CALL_TYPE VARCHAR(8000),
    IMSI VARCHAR(8000),
    MSISDN VARCHAR(8000),
    APN_NETWORK VARCHAR(8000),
    DEVICE_TAC_CODE VARCHAR(8000),
    NUMBER_OF_CALLS INTEGER,
    CHARGED_SMS INTEGER,
    CHARGED_MINUTES NUMBER(15,5),
    CHARGED_MB NUMBER(15,5),
    SETTLEMENT_GROSS_CHARGE_USD NUMBER(15,5),
    
    -- COLUNAS PREENCHIDAS PELO LOADER
    DIRECTION CHAR(3),
    SOURCE_FILE_NAME VARCHAR(255), -- Arquivo de origem da informacao
  	SOURCE_SYSTEM VARCHAR(255), -- Sistema de Origem (DCH, BO, etc)
  	JOB_NAME VARCHAR(255), -- Job que realizou a carga
  	ETL_BATCH_ID VARCHAR(50), -- ID de Batch
  	
  	-- COLUNAS PREENCHIDAS AUTOMATICAMENTE
  	ROW_CREATE_TS TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP, -- TIMESTAMP em que a informacao foi carregada no Teradata
	ROW_CREATE_USER VARCHAR(128) DEFAULT USER -- Usuario que carregou a informacao
);