-- INSERIR DADOS DA STAGING PARA A TABELA FINAL
SET QUERY_BAND = 'name=INT_ROAMING;' FOR SESSION;
INSERT INTO U_INT_ATACADO.FCT_RMNG_INT
	SELECT
		TAP_FILE_CURRENT_PROCESSING_DATE,
		DATE_CALL,
		DIRECTION,
		PMN_SETTLEMENT_TADIG_CODE,
		CALL_TYPE,
		IMSI,
		MSISDN,
		DEVICE_TAC_CODE,
		APN_NETWORK,
		NUMBER_OF_CALLS AS NUMBER_OF_EVENTS,
		CHARGED_SMS,
		CHARGED_MINUTES,
		CHARGED_MB,
		SETTLEMENT_GROSS_CHARGE_USD,
		SOURCE_FILE_NAME,
	  	SOURCE_SYSTEM,
	  	JOB_NAME,
	  	ETL_BATCH_ID,
	  	ROW_CREATE_TS,
		ROW_CREATE_USER
	FROM U_INT_ATACADO.STG_RMNG_INT_INB;
DROP TABLE U_INT_ATACADO.STG_RMNG_INT_INB;
	
INSERT INTO U_INT_ATACADO.FCT_RMNG_INT
	SELECT
		TAP_FILE_CURRENT_PROCESSING_DATE,
		DATE_CALL,
		DIRECTION,
		PMN_SETTLEMENT_TADIG_CODE,
		CALL_TYPE,
		IMSI,
		MSISDN,
		DEVICE_TAC_CODE,
		APN_NETWORK,
		NUMBER_OF_CALLS AS NUMBER_OF_EVENTS,
		CHARGED_SMS,
		CHARGED_MINUTES,
		CHARGED_MB,
		SETTLEMENT_GROSS_CHARGE_USD,
		SOURCE_FILE_NAME,
	  	SOURCE_SYSTEM,
	  	JOB_NAME,
	  	ETL_BATCH_ID,
	  	ROW_CREATE_TS,
		ROW_CREATE_USER
	FROM U_INT_ATACADO.STG_RMNG_INT_OUT;
DROP TABLE U_INT_ATACADO.STG_RMNG_INT_OUT;