-- TABELA FINAL ROAMING INTERNACIONAL

SET QUERY_BAND = 'name=INT_ROAMING;' FOR SESSION;
--DROP TABLE U_INT_ATACADO.FCT_RMNG_INT;

CREATE MULTISET TABLE U_INT_ATACADO.FCT_RMNG_INT, FALLBACK,
	NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
	MAP = TD_MAP1
(
	-- Datas
	TAP_FILE_CURRENT_PROCESSING_DATE DATE NOT NULL, -- Data em que o TAP foi processado pela DCH. UTC-0
  	DATE_CALL DATE NOT NULL, -- Data em que a chamada ocorreu. UTC-0

  	-- Dimens�es e chaves de neg�cio
  	DIRECTION CHAR(3) NOT NULL, -- INB = INBOUND / OUT = OUTBOUND
  	PMN_TADIG_CODE CHAR(5) NOT NULL, -- C�digo da Operadora -> XXXXX Ex.: BRATA
  	CALL_TYPE CHAR(6) NOT NULL, -- MOC/MTC/SMS-MO/SMS-MT/GPRS/SS
  	IMSI VARCHAR(15) NOT NULL CHECK (IMSI BETWEEN '000000000000000' AND '999999999999999'),
  	MSISDN VARCHAR(20), -- Padrao internacional: 55219XXXXXXXX. Nem sempre vem bem formatado no TAP
  	DEVICE_TAC_CODE VARCHAR(20), -- Padrao: XXXXXXXX. Nem sempre vem bem formatado no TAP
  	APN_NETWORK VARCHAR(255), -- APN utilizada pelo aparelho em chamadas GPRS
  	
  	-- Metricas de uso
  	NUMBER_OF_EVENTS INTEGER CHECK(NUMBER_OF_EVENTS >= 0),
  	CHARGED_SMS SMALLINT CHECK(CHARGED_SMS >= 0),
  	CHARGED_MINUTES DECIMAL(15,5) CHECK(CHARGED_MINUTES >= 0),
  	CHARGED_MEGABYTES  DECIMAL(15,5) CHECK(CHARGED_MEGABYTES  >= 0),
  	
  	-- Metricas financeiras
  	SETTLEMENT_GROSS_CHARGE_USD DECIMAL(15,5) CHECK(SETTLEMENT_GROSS_CHARGE_USD >= 0),
  	
  	-- Auditoria
  	SOURCE_FILE_NAME VARCHAR(255), -- Arquivo de origem da informa��o
  	SOURCE_SYSTEM VARCHAR(255), -- Sistema de Origem (DCH, BO, etc)
  	JOB_NAME VARCHAR(255), -- Job que realizou a carga
  	ETL_BATCH_ID VARCHAR(50), -- ID de Batch
  	ROW_CREATE_TS TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP, -- TIMESTAMP em que a informacao foi carregada no Teradata
	ROW_CREATE_USER VARCHAR(128) DEFAULT USER -- Usu�rio que carregou a informacao
)
PRIMARY INDEX (DATE_CALL, DIRECTION, PMN_TADIG_CODE)
PARTITION BY RANGE_N(DATE_CALL BETWEEN 	DATE '2024-01-01'
                               AND 		DATE '2199-12-31'
                               EACH 	INTERVAL '1' MONTH);
