-- SEGMENTACAO USUARIOS VIVO
SET QUERY_BAND = 'name=INT_ROAMING;' FOR SESSION;

/*
    -----------------------PASSO 1-----------------------
    CRIACAO DAS VIEWS DO NACIONAL E INTERNACIONAL
*/
DROP VIEW U_INT_ATACADO.VW_LNHA_SEG_INT;
CREATE VIEW U_INT_ATACADO.VW_LNHA_SEG_INT AS(
	SELECT DISTINCT
		YEAR(DATE_CALL) AS ANO,
		MONTH(DATE_CALL) AS MES,
		CAST(IMSI AS BIGINT) AS IMSI,
		CAST(RIGHT(MSISDN, 11) AS BIGINT) AS MSISDN
	FROM U_INT_ATACADO.FCT_RMNG_INT
	WHERE 1=1
		AND MSISDN IS NOT NULL
		AND DIRECTION = 'OUT'
		AND REGEXP_SIMILAR(MSISDN, '55[1-9]{2}9[0-9]{8}$') = 1
		OR REGEXP_SIMILAR(MSISDN, '[1-9]{2}9[0-9]{8}$') = 1
);
--SELECT TOP 10 * FROM U_INT_ATACADO.VW_LNHA_SEG_INT;

DROP VIEW U_INT_ATACADO.VW_LNHA_SEG_NAT;
CREATE VIEW U_INT_ATACADO.VW_LNHA_SEG_NAT AS(
	SELECT DISTINCT
		YEAR(DATE_CALL) AS ANO,
		MONTH(DATE_CALL) AS MES,
		CAST(IMSI AS BIGINT) AS IMSI,
		CAST(RIGHT(MSISDN, 11) AS BIGINT) AS MSISDN
	FROM U_INT_ATACADO.FCT_RMNG_NAT
	WHERE 1=1
		AND MSISDN IS NOT NULL
		AND DIRECTION = 'OUT'
		AND REGEXP_SIMILAR(MSISDN, '55[1-9]{2}9[0-9]{8}$') = 1
		OR REGEXP_SIMILAR(MSISDN, '[1-9]{2}9[0-9]{8}$') = 1
);
--SELECT TOP 10 * FROM U_INT_ATACADO.VW_LNHA_SEG_NAT;

/*
    -----------------------PASSO 2-----------------------
    CRIACAO DO PARQUE DE ROAMING COMPLETO
*/
DROP TABLE U_INT_ATACADO.PRQE_RMNG_OUT_DCH;
CREATE TABLE U_INT_ATACADO.PRQE_RMNG_OUT_DCH AS(
	SELECT
		* 
	FROM U_INT_ATACADO.VW_LNHA_SEG_INT
	
	UNION 
	
	SELECT
		* 
	FROM U_INT_ATACADO.VW_LNHA_SEG_NAT
) WITH DATA PRIMARY INDEX(MSISDN, ANO, MES);

/*
    -----------------------PASSO 3-----------------------
    COLETA DAS INFORMACOES DAS LINHAS DO PARQUE DE ROAMING
    NO PARQUE OFICIAL DA VIVO
*/
DROP TABLE U_INT_ATACADO.PRQE_RMNG_OUT_FINAL;
CREATE TABLE U_INT_ATACADO.PRQE_RMNG_OUT_FINAL AS (
	SELECT
	    A.IMSI AS IMSI,
	    A.MSISDN AS NR_TLFN,
	    B.DS_PRDT AS SEGMENTO,
	    B.ID_PSSA AS ID_PSSA,
	    B.ID_LNHA AS ID_LNHA,
	    B.ID_PLNO AS ID_PLNO,
	    YEAR(B.DT_FOTO_LNHA) AS ANO,
	    MONTH(B.DT_FOTO_LNHA) AS MES,
	    --B.ID_CNTA AS ID_CNTA,
	    --B.CD_CNTA AS CD_CNTA,
	    --B.DT_PRMR_ATVC_LNHA AS DT_PRMR_ATVC_LNHA,
	    CASE
	        WHEN B.DS_MODL_ORIG NOT LIKE ALL
	            (
	                '%A%','%B%','%C%','%D%','%E%','%F%','%G%','%H%','%I%','%J%','%K%',
	                '%L%','%M%','%N%','%O%','%P%','%Q%','%R%','%S%','%T%','%U%','%V%',
	                '%W%','%X%','%Y%','%Z%','%#%','%/%','%@%','%\%','%-%','%.%','% %','%+%'
	            )
	            THEN Cast(B.DS_MODL_ORIG AS DECIMAL(8)) ELSE 0
	    END AS NR_TAC,
	    C.DS_PLNO AS PLANO
	FROM U_INT_ATACADO.PRQE_RMNG_OUT_DCH A
	LEFT JOIN P_VIEDB.VW_FAT_PRQE_LNHA_DSPT B
		ON A.MSISDN = B.NR_TLFN
			AND A.ANO = YEAR(B.DT_FOTO_LNHA)
			AND A.MES = MONTH(B.DT_FOTO_LNHA)
			AND A.MSISDN IS NOT NULL
	LEFT JOIN P_VIEDB.VW_DIM_PLNO C
		ON B.ID_PLNO = C.ID_PLNO
	WHERE 1=1
	    AND B.FL_PRQE_OFCL = 1
	QUALIFY ROW_NUMBER() OVER (PARTITION BY NR_TLFN, ANO, MES ORDER BY B.DT_FOTO_LNHA DESC) = 1
) WITH DATA PRIMARY INDEX (IMSI, NR_TLFN);
--SELECT TOP 10 * FROM U_INT_ATACADO.PRQE_RMNG_OUT_FINAL;


/*
    TESTAR
*/
SET QUERY_BAND = 'name=INT_ROAMING;' FOR SESSION;
CREATE VOLATILE TABLE VT_PRE_SEGMENTACAO AS (
    SELECT 
        YEAR(DATE_CALL) AS ANO,
        MONTH(DATE_CALL) AS MES,
        CAST(IMSI AS BIGINT) AS IMSI,
        TRYCAST(RIGHT(MSISDN, 11) AS BIGINT) AS MSISDN
    FROM U_INT_ATACADO.FCT_RMNG_INT
    WHERE 1=1
        AND DIRECTION = 'OUT'
        AND MSISDN IS NOT NULL
        AND (
            LENGTH(TRIM(MSISDN)) = 11 -- Validação simples de tamanho
            OR MSISDN LIKE '55%'      -- Validação simples de prefixo
        )
    
    UNION
    
    SELECT 
        YEAR(DATE_CALL) AS ANO,
        MONTH(DATE_CALL) AS MES,
        CAST(IMSI AS BIGINT) AS IMSI,
        TRYCAST(RIGHT(MSISDN, 11) AS BIGINT) AS MSISDN
    FROM U_INT_ATACADO.FCT_RMNG_NAT
    WHERE 1=1
        AND DIRECTION = 'OUT'
        AND MSISDN IS NOT NULL
        AND (
            LENGTH(TRIM(MSISDN)) = 11
            OR MSISDN LIKE '55%'
        )
) WITH DATA 
PRIMARY INDEX (MSISDN, ANO, MES)
ON COMMIT PRESERVE ROWS;
COLLECT STATS ON VT_PRE_SEGMENTACAO COLUMN (MSISDN, ANO, MES);

CREATE TABLE U_INT_ATACADO.PRQE_RMNG_OUT_FINAL, 
FALLBACK,
NO BEFORE JOURNAL,
NO AFTER JOURNAL
AS (
    SELECT
        A.IMSI,
        A.MSISDN AS NR_TLFN,
        B.DS_PRDT AS SEGMENTO,
        B.ID_PSSA,
        B.ID_LNHA,
        B.ID_PLNO,
        A.ANO,
        A.MES,
        COALESCE(TRYCAST(B.DS_MODL_ORIG AS DECIMAL(8,0)), 0) AS NR_TAC, --Limpar TACs sujos (retorna NULL se falhar)
        C.DS_PLNO AS PLANO
    FROM VT_PRE_SEGMENTACAO A
    INNER JOIN P_VIEDB.VW_FAT_PRQE_LNHA_DSPT B
        ON A.MSISDN = TRYCAST(B.NR_TLFN AS BIGINT)
        AND A.ANO = YEAR(B.DT_FOTO_LNHA)
        AND A.MES = MONTH(B.DT_FOTO_LNHA)
    LEFT JOIN P_VIEDB.VW_DIM_PLNO C
        ON B.ID_PLNO = C.ID_PLNO
    WHERE 1=1
        AND B.FL_PRQE_OFCL = 1
    -- Mantém apenas o registro mais recente da foto da linha no mês
    QUALIFY ROW_NUMBER() OVER (PARTITION BY A.MSISDN, A.ANO, A.MES ORDER BY B.DT_FOTO_LNHA DESC) = 1
) WITH DATA 
PRIMARY INDEX (IMSI, NR_TLFN);

-- Limpeza
DROP TABLE VT_PRE_SEGMENTACAO;