--RESUMOS PARA FATURAMENTO CDG (AJUSTAR)
--ESSAS VIEWS SERVEM PARA ALIMENTAR O DASHBOARD DE PROVISAO APENAS

SET QUERY_BAND = 'name=INT_ROAMING;' FOR SESSION;
DROP VIEW U_INT_ATACADO.VW_RSM_CDG_INT;
CREATE VIEW U_INT_ATACADO.VW_RSM_CDG_INT AS (
	SELECT
		YEAR(A.DATE_CALL) AS ANO,
		MONTH(A.DATE_CALL) AS MES,
		CASE 
			WHEN LEFT(CAST(B.NR_TLFN AS VARCHAR(11)), 2) IS NULL
				THEN 'NI'
			ELSE LEFT(CAST(B.NR_TLFN AS VARCHAR(11)), 2)
		END AS CN,
		A.CALL_TYPE,
		A.PMN_TADIG_CODE,
		C.PMN_COUNTRY,
		C.PMN_NAME,
		C.PMN_TYPE,
		REGEXP_SIMILAR(A.MSISDN, '55[1-9]{2}9[0-9]{8}$') AS REGEX,
        COALESCE(B.SEGMENTO, B.PLANO, 'NI') AS SEGMENTO,
		SUM(A.SETTLEMENT_GROSS_CHARGE_USD) AS CUSTO_USD,
		COUNT(DISTINCT A.IMSI) AS IMSI_COUNT
	FROM U_INT_ATACADO.FCT_RMNG_INT A
	
	LEFT JOIN U_INT_ATACADO.PRQE_RMNG_OUT_FINAL B
	ON 
		A.IMSI = B.IMSI
		AND YEAR(A.DATE_CALL) = B.ANO
		AND MONTH(A.DATE_CALL) = B.MES
		
	LEFT JOIN U_INT_ATACADO.DM_OPERATORS C
		ON A.PMN_TADIG_CODE = C.PMN_TADIG_CODE
		
	WHERE 1=1
		AND DATE_CALL >= '2025-01-01'
		AND DIRECTION = 'OUT'
	GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
);
--SELECT * FROM U_INT_ATACADO.VW_RSM_CDG_INT;



DROP VIEW U_INT_ATACADO.VW_RSM_CDG_INT;
CREATE VIEW U_INT_ATACADO.VW_RSM_CDG_INT AS (
	SELECT
		YEAR(A.DATE_CALL) AS ANO,
		MONTH(A.DATE_CALL) AS MES,
		
		CASE 
			WHEN LEFT(CAST(B.NR_TLFN AS VARCHAR(11)), 2) IS NULL
				THEN 'NI'
			ELSE LEFT(CAST(B.NR_TLFN AS VARCHAR(11)), 2)
		END AS CN,
		
		A.CALL_TYPE,
		A.PMN_TADIG_CODE,
		C.PMN_COUNTRY,
		C.PMN_NAME,
		C.PMN_TYPE,
		REGEXP_SIMILAR(A.MSISDN, '55[1-9]{2}9[0-9]{8}$') AS REGEX,
		CASE 
			WHEN COALESCE(B.SEGMENTO, B.PLANO) IS NULL
				THEN 'NI'
			ELSE COALESCE(B.SEGMENTO, B.PLANO)
		END AS SEGMENTO,
		
		-- CUSTOS
		SUM(A.SETTLEMENT_GROSS_CHARGE_USD) AS CUSTO_USD,
		
		CASE
			WHEN (A.CALL_TYPE = 'GPRS' AND D.DEAL_FINAL >= A.DATE_CALL)
				THEN COALESCE(
					SUM(A.CHARGED_MEGABYTES * D.TARIFF_DATA),
					SUM(A.SETTLEMENT_GROSS_CHARGE_USD)
					)
				
			WHEN (A.CALL_TYPE = 'MOC' AND D.DEAL_FINAL >= A.DATE_CALL)
				THEN COALESCE(
					SUM(A.CHARGED_MINUTES * D.TARIFF_MOC),
					SUM(A.SETTLEMENT_GROSS_CHARGE_USD)
					)
				
			WHEN (A.CALL_TYPE = 'MTC' AND D.DEAL_FINAL >= A.DATE_CALL)
				THEN COALESCE(
					SUM(A.CHARGED_MINUTES * D.TARIFF_MTC),
					SUM(A.SETTLEMENT_GROSS_CHARGE_USD)
					)
				
			WHEN (A.CALL_TYPE = 'SMS-MO' AND D.DEAL_FINAL >= A.DATE_CALL)
				THEN COALESCE(
					SUM(A.CHARGED_SMS * D.TARIFF_SMSMO),
					SUM(A.SETTLEMENT_GROSS_CHARGE_USD)
					)
		END AS CUSTO_RECALCULADO_USD,
		
		-- CONTAGEM DE IMSIs
		COUNT(DISTINCT A.IMSI) AS IMSI_COUNT
	FROM U_INT_ATACADO.FCT_RMNG_INT A
	
	LEFT JOIN U_INT_ATACADO.PRQE_RMNG_OUT_FINAL B
	ON 
		A.IMSI = B.IMSI
		AND YEAR(A.DATE_CALL) = B.ANO
		AND MONTH(A.DATE_CALL) = B.MES
		
	LEFT JOIN U_INT_ATACADO.DM_OPERATORS C
		ON A.PMN_TADIG_CODE = C.PMN_TADIG_CODE
	
	LEFT JOIN U_INT_ATACADO.FCT_TGR_TARIFFS D
		ON A.PMN_TADIG_CODE = D.PMN_SETTLEMENT_TADIG_CODE
	
	WHERE 1=1
		AND A.DATE_CALL >= '2025-01-01'
		AND A.DIRECTION = 'OUT'
		-- AND D.DEAL_FINAL >= A.DATE_CALL
	GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
);

Executed as Single statement.  Failed [3504 : HY000] Selected non-aggregate values must be part of the associated group. 
Elapsed time = 00:00:00.033 
 
STATEMENT 1: Select Statement failed. 