--RESUMOS PARA FATURAMENTO CDG (AJUSTAR)
--ESSAS VIEWS SERVEM PARA ALIMENTAR O DASHBOARD DE PROVISAO APENAS
SET
	QUERY_BAND = 'name=INT_ROAMING;' FOR SESSION;

/*
----------------------------------INTERNACIONAL----------------------------------
 */
REPLACE VIEW U_INT_ATACADO.VW_RSM_CDG_INT AS (
	SELECT
		YEAR (A.DATE_CALL) AS ANO,
		MONTH (A.DATE_CALL) AS MES,
		CASE
			WHEN LEFT (CAST(B.NR_TLFN AS VARCHAR(11)), 2) IS NULL THEN 'NI'
			ELSE LEFT (CAST(B.NR_TLFN AS VARCHAR(11)), 2)
		END AS CN,
		A.CALL_TYPE,
		A.PMN_TADIG_CODE,
		C.PMN_COUNTRY,
		C.PMN_NAME,
		C.PMN_TYPE,
		REGEXP_SIMILAR (A.MSISDN, '55[1-9]{2}9[0-9]{8}$') AS REGEX,
		CASE
			WHEN COALESCE(B.SEGMENTO, B.PLANO) IS NULL THEN 'NI'
			ELSE COALESCE(B.SEGMENTO, B.PLANO)
		END AS SEGMENTO,
		-- CUSTOS
		SUM(A.SETTLEMENT_GROSS_CHARGE_USD) AS CUSTO_USD,
		SUM(
			CASE
				WHEN A.CALL_TYPE = 'GPRS' THEN COALESCE(
					CAST(A.CHARGED_MEGABYTES AS NUMBER (15, 5)) * CAST(D.TARIFF_DATA AS NUMBER (15, 5)),
					A.SETTLEMENT_GROSS_CHARGE_USD
				)
				WHEN A.CALL_TYPE = 'MOC' THEN COALESCE(
					CAST(A.CHARGED_MINUTES AS NUMBER (15, 5)) * CAST(D.TARIFF_MOC AS NUMBER (15, 5)),
					A.SETTLEMENT_GROSS_CHARGE_USD
				)
				WHEN A.CALL_TYPE = 'MTC' THEN COALESCE(
					CAST(A.CHARGED_MINUTES AS NUMBER (15, 5)) * CAST(D.TARIFF_MTC AS NUMBER (15, 5)),
					A.SETTLEMENT_GROSS_CHARGE_USD
				)
				WHEN A.CALL_TYPE = 'SMS-MO' THEN COALESCE(
					CAST(A.CHARGED_SMS AS NUMBER (15, 5)) * CAST(D.TARIFF_SMSMO AS NUMBER (15, 5)),
					A.SETTLEMENT_GROSS_CHARGE_USD
				)
			END
		) AS CUSTO_RECALCULADO_USD,
		-- TARIFAS
		MAX(D.TARIFF_DATA) AS TARIFF_DATA,
		MAX(D.TARIFF_MOC) AS TARIFF_MOC,
		MAX(D.TARIFF_MTC) AS TARIFF_MTC,
		MAX(D.TARIFF_SMSMO) AS TARIFF_SMSMO,
		-- CONTAGEM DE IMSIs
		COUNT(DISTINCT A.IMSI) AS IMSI_COUNT
	FROM
		U_INT_ATACADO.FCT_RMNG_INT A
		LEFT JOIN U_INT_ATACADO.PRQE_RMNG_OUT_FINAL B ON A.IMSI = B.IMSI
		AND YEAR (A.DATE_CALL) = B.ANO
		AND MONTH (A.DATE_CALL) = B.MES
		LEFT JOIN U_INT_ATACADO.DM_OPERATORS C ON A.PMN_TADIG_CODE = C.PMN_TADIG_CODE
		LEFT JOIN U_INT_ATACADO.FCT_TGR_TARIFFS D ON A.PMN_TADIG_CODE = D.PMN_SETTLEMENT_TADIG_CODE
		AND D.DEAL_FINAL >= A.DATE_CALL
		AND D.DIRECTION = 'OB'
		AND D.DEAL_STATUS = 'Closed'
	WHERE
		1 = 1
		AND A.DATE_CALL >= '2025-01-01'
		AND A.DIRECTION = 'OUT'
	GROUP BY
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
		10
);

/*
----------------------------------NACIONAL----------------------------------
 */
REPLACE VIEW U_INT_ATACADO.VW_RSM_CDG_NAT AS (
	SELECT
		YEAR (A.DATE_CALL) AS ANO,
		MONTH (A.DATE_CALL) AS MES,
		CASE
			WHEN LEFT (CAST(B.NR_TLFN AS VARCHAR(11)), 2) IS NULL THEN 'NI'
			ELSE LEFT (CAST(B.NR_TLFN AS VARCHAR(11)), 2)
		END AS CN,
		A.CALL_TYPE,
		A.PMN_TADIG_CODE,
		C.PMN_COUNTRY,
		C.PMN_NAME,
		C.PMN_TYPE,
		REGEXP_SIMILAR (A.MSISDN, '55[1-9]{2}9[0-9]{8}$') AS REGEX,
		CASE
			WHEN COALESCE(B.SEGMENTO, B.PLANO) IS NULL THEN 'NI'
			ELSE COALESCE(B.SEGMENTO, B.PLANO)
		END AS SEGMENTO,
		-- CUSTOS
		SUM(A.SETTLEMENT_GROSS_CHARGE_BRL) AS CUSTO_BRL,
		-- CONTAGEM DE IMSIs
		COUNT(DISTINCT A.IMSI) AS IMSI_COUNT
	FROM
		U_INT_ATACADO.FCT_RMNG_NAT A
		LEFT JOIN U_INT_ATACADO.PRQE_RMNG_OUT_FINAL B ON A.IMSI = B.IMSI
		AND YEAR (A.DATE_CALL) = B.ANO
		AND MONTH (A.DATE_CALL) = B.MES
		LEFT JOIN U_INT_ATACADO.DM_OPERATORS C ON A.PMN_TADIG_CODE = C.PMN_TADIG_CODE
	WHERE
		1 = 1
		AND A.DATE_CALL >= '2025-01-01'
		AND A.DIRECTION = 'OUT'
	GROUP BY
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
		10
);