--RESUMOS PARA FATURAMENTO CDG (AJUSTAR)
--ESSAS VIEWS SERVEM PARA ALIMENTAR O DASHBOARD DE PROVISAO APENAS

SET QUERY_BAND = 'name=INT_ROAMING;' FOR SESSION;
DROP VIEW U_INT_ATACADO.VW_RSM_CDG_INT;
CREATE VIEW U_INT_ATACADO.VW_RSM_CDG_INT AS (
	SELECT
		YEAR(A.DATE_CALL) AS ANO,
		MONTH(A.DATE_CALL) AS MES,
		CASE 
			WHEN LEFT(CAST(B.NR_TLFN AS VARCHAR(11)), 2) IS NULL
				THEN 'NI'
			ELSE LEFT(CAST(B.NR_TLFN AS VARCHAR(11)), 2)
		END AS CN,
		A.CALL_TYPE,
		A.PMN_TADIG_CODE,
		C.PMN_COUNTRY,
		C.PMN_NAME,
		C.PMN_TYPE,
		REGEXP_SIMILAR(A.MSISDN, '55[1-9]{2}9[0-9]{8}$') AS REGEX,
        COALESCE(B.SEGMENTO, B.PLANO, 'NI') AS SEGMENTO,
		SUM(A.SETTLEMENT_GROSS_CHARGE_USD) AS CUSTO_USD,
		COUNT(DISTINCT A.IMSI) AS IMSI_COUNT
	FROM U_INT_ATACADO.FCT_RMNG_INT A
	
	LEFT JOIN U_INT_ATACADO.PRQE_RMNG_OUT_FINAL B
	ON 
		A.IMSI = B.IMSI
		AND YEAR(A.DATE_CALL) = B.ANO
		AND MONTH(A.DATE_CALL) = B.MES
		
	LEFT JOIN U_INT_ATACADO.DM_OPERATORS C
		ON A.PMN_TADIG_CODE = C.PMN_TADIG_CODE
		
	WHERE 1=1
		AND DATE_CALL >= '2025-01-01'
		AND DIRECTION = 'OUT'
	GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
);
--SELECT * FROM U_INT_ATACADO.VW_RSM_CDG_INT;