-- CONFERENCIA QTDE IMSI MCM
DROP VIEW U_INT_ATACADO.VW_RMNG_MCM_CHK;
CREATE VIEW U_INT_ATACADO.VW_RMNG_MCM_CHK AS(
	SELECT
		YEAR(DATE_CALL) AS ANO,
		MONTH(DATE_CALL) AS MES,
		APN_NETWORK,
		COUNT(DISTINCT IMSI) AS IMSI_COUNT
	FROM U_INT_ATACADO.FCT_RMNG_INT
	WHERE 1=1
		AND DATE_CALL > '2025-01-01'
		AND APN_NETWORK = 'zap.vivo.com.br'
		AND DIRECTION = 'OUT'
		AND CALL_TYPE = 'GPRS'
		AND CHARGED_MEGABYTES > 0
	GROUP BY 1, 2, 3
);
SELECT * FROM U_INT_ATACADO.VW_RMNG_MCM_CHK;