-- TABELA STAGING - ROAMING INTERNACIONAL INBOUND

SET QUERY_BAND = 'name=INT_ROAMING;' FOR SESSION;
CREATE MULTISET TABLE U_INT_ATACADO.STG_RMNG_INT_INB(
	
	-- COLUNAS CARREGADAS DA DCH
	TAP_FILE_CURRENT_PROCESSING_DATE TIMESTAMP,
    DATE_CALL TIMESTAMP,
    PMN_SETTLEMENT_TADIG_CODE VARCHAR(8000),
    CALL_TYPE VARCHAR(8000),
    IMSI VARCHAR(8000),
    MSISDN VARCHAR(8000),
    APN_NETWORK VARCHAR(8000),
    DEVICE_TAC_CODE VARCHAR(8000),
    NUMBER_OF_CALLS INTEGER,
    CHARGED_SMS INTEGER,
    CHARGED_MINUTES NUMBER(15,5),
    CHARGED_MB NUMBER(15,5),
    SETTLEMENT_GROSS_CHARGE_USD NUMBER(15,5),
    
    -- COLUNAS PREENCHIDAS PELO LOADER
    DIRECTION CHAR(3),
    SOURCE_FILE_NAME VARCHAR(255), -- Arquivo de origem da informação
  	SOURCE_SYSTEM VARCHAR(255), -- Sistema de Origem (DCH, BO, etc)
  	JOB_NAME VARCHAR(255), -- Job que realizou a carga
  	ETL_BATCH_ID VARCHAR(50), -- ID de Batch
  	
  	-- COLUNAS PREENCHIDAS AUTOMATICAMENTE
  	ROW_CREATE_TS TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP, -- TIMESTAMP em que a informação foi carregada no Teradata
	ROW_CREATE_USER VARCHAR(128) DEFAULT USER -- Usuário que carregou a informação
);

-- TABELA FINAL ROAMING INTERNACIONAL
--DROP TABLE U_INT_ATACADO.FCT_RMNG_INT;
CREATE MULTISET TABLE U_INT_ATACADO.FCT_RMNG_INT, FALLBACK,
	NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
	MAP = TD_MAP1
(
	-- Datas
	TAP_FILE_CURRENT_PROCESSING_DATE DATE NOT NULL, -- Data em que o TAP foi processado pela DCH. UTC-0
  	DATE_CALL DATE NOT NULL, -- Data em que a chamada ocorreu. UTC-0

  	-- Dimensões e chaves de negócio
  	DIRECTION CHAR(3) NOT NULL, -- INB = INBOUND / OUT = OUTBOUND
  	PMN_TADIG_CODE CHAR(5) NOT NULL, -- Código da Operadora -> XXXXX Ex.: BRATA
  	CALL_TYPE CHAR(6) NOT NULL, -- MOC/MTC/SMS-MO/SMS-MT/GPRS/SS
  	IMSI VARCHAR(15) NOT NULL CHECK (IMSI BETWEEN '000000000000000' AND '999999999999999'),
  	MSISDN VARCHAR(20), -- Padrão internacional: 55219XXXXXXXX. Nem sempre vem bem formatado no TAP
  	DEVICE_TAC_CODE VARCHAR(20), -- Padrão: XXXXXXXX. Nem sempre vem bem formatado no TAP
  	APN_NETWORK VARCHAR(255), -- APN utilizada pelo aparelho em chamadas GPRS
  	
  	-- Métricas de uso
  	NUMBER_OF_EVENTS INTEGER CHECK(NUMBER_OF_EVENTS >= 0),
  	CHARGED_SMS SMALLINT CHECK(CHARGED_SMS >= 0),
  	CHARGED_MINUTES DECIMAL(15,5) CHECK(CHARGED_MINUTES >= 0),
  	CHARGED_MEGABYTES  DECIMAL(15,5) CHECK(CHARGED_MEGABYTES  >= 0),
  	
  	-- Métricas financeiras
  	SETTLEMENT_GROSS_CHARGE_USD DECIMAL(15,5) CHECK(SETTLEMENT_GROSS_CHARGE_USD >= 0),
  	
  	-- Auditoria
  	SOURCE_FILE_NAME VARCHAR(255), -- Arquivo de origem da informação
  	SOURCE_SYSTEM VARCHAR(255), -- Sistema de Origem (DCH, BO, etc)
  	JOB_NAME VARCHAR(255), -- Job que realizou a carga
  	ETL_BATCH_ID VARCHAR(50), -- ID de Batch
  	ROW_CREATE_TS TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP, -- TIMESTAMP em que a informação foi carregada no Teradata
	ROW_CREATE_USER VARCHAR(128) DEFAULT USER -- Usuário que carregou a informação
)
PRIMARY INDEX (DATE_CALL, DIRECTION, PMN_TADIG_CODE)
PARTITION BY RANGE_N(DATE_CALL BETWEEN 	DATE '2024-01-01'
                               AND 		DATE '2199-12-31'
                               EACH 	INTERVAL '1' MONTH);

                               
-- INSERIR DADOS DA STAGING PARA A TABELA FINAL
INSERT INTO U_INT_ATACADO.FCT_RMNG_INT
	SELECT
		TAP_FILE_CURRENT_PROCESSING_DATE,
		DATE_CALL,
		DIRECTION,
		PMN_SETTLEMENT_TADIG_CODE,
		CALL_TYPE,
		IMSI,
		MSISDN,
		DEVICE_TAC_CODE,
		APN_NETWORK,
		NUMBER_OF_CALLS AS NUMBER_OF_EVENTS,
		CHARGED_SMS,
		CHARGED_MINUTES,
		CHARGED_MB,
		SETTLEMENT_GROSS_CHARGE_USD,
		SOURCE_FILE_NAME,
	  	SOURCE_SYSTEM,
	  	JOB_NAME,
	  	ETL_BATCH_ID,
	  	ROW_CREATE_TS,
		ROW_CREATE_USER
	FROM U_INT_ATACADO.fSTG_RMNG_INT_INB;
DROP TABLE U_INT_ATACADO.fSTG_RMNG_INT_INB;
	
INSERT INTO U_INT_ATACADO.FCT_RMNG_INT
	SELECT
		TAP_FILE_CURRENT_PROCESSING_DATE,
		DATE_CALL,
		DIRECTION,
		PMN_SETTLEMENT_TADIG_CODE,
		CALL_TYPE,
		IMSI,
		MSISDN,
		DEVICE_TAC_CODE,
		APN_NETWORK,
		NUMBER_OF_CALLS AS NUMBER_OF_EVENTS,
		CHARGED_SMS,
		CHARGED_MINUTES,
		CHARGED_MB,
		SETTLEMENT_GROSS_CHARGE_USD,
		SOURCE_FILE_NAME,
	  	SOURCE_SYSTEM,
	  	JOB_NAME,
	  	ETL_BATCH_ID,
	  	ROW_CREATE_TS,
		ROW_CREATE_USER
	FROM U_INT_ATACADO.fSTG_RMNG_INT_OUT;
DROP TABLE U_INT_ATACADO.fSTG_RMNG_INT_OUT;


-- CONFERÊNCIA QTDE IMSI MCM
DROP VIEW U_INT_ATACADO.VW_RMNG_MCM_CHK;
CREATE VIEW U_INT_ATACADO.VW_RMNG_MCM_CHK AS(
	SELECT
		YEAR(DATE_CALL) AS ANO,
		MONTH(DATE_CALL) AS MES,
		APN_NETWORK,
		COUNT(DISTINCT IMSI) AS IMSI_COUNT
	FROM U_INT_ATACADO.FCT_RMNG_INT
	WHERE 1=1
		AND DATE_CALL > '2025-01-01'
		AND APN_NETWORK = 'zap.vivo.com.br'
		AND DIRECTION = 'OUT'
		AND CALL_TYPE = 'GPRS'
		AND CHARGED_MEGABYTES > 0
	GROUP BY 1, 2, 3
);
SELECT * FROM U_INT_ATACADO.VW_RMNG_MCM_CHK;


-- SEGMENTACAO USUARIOS VIVO
DROP VIEW U_INT_ATACADO.VW_LNHA_SEG_INT;
CREATE VIEW U_INT_ATACADO.VW_LNHA_SEG_INT AS(
	SELECT DISTINCT
		YEAR(DATE_CALL) AS ANO,
		MONTH(DATE_CALL) AS MES,
		CAST(IMSI AS BIGINT) AS IMSI,
		CAST(RIGHT(MSISDN, 11) AS BIGINT) AS MSISDN
	FROM U_INT_ATACADO.FCT_RMNG_INT
	WHERE 1=1
		AND MSISDN IS NOT NULL
		AND DIRECTION = 'OUT'
		AND REGEXP_SIMILAR(MSISDN, '55[1-9]{2}9[0-9]{8}$') = 1
		OR REGEXP_SIMILAR(MSISDN, '[1-9]{2}9[0-9]{8}$') = 1
);
SELECT TOP 10 * FROM U_INT_ATACADO.VW_LNHA_SEG_INT;

DROP VIEW U_INT_ATACADO.VW_LNHA_SEG_NAT;
CREATE VIEW U_INT_ATACADO.VW_LNHA_SEG_NAT AS(
	SELECT DISTINCT
		YEAR(DATE_CALL) AS ANO,
		MONTH(DATE_CALL) AS MES,
		CAST(IMSI AS BIGINT) AS IMSI,
		CAST(RIGHT(MSISDN, 11) AS BIGINT) AS MSISDN
	FROM U_INT_ATACADO.FCT_RMNG_NAT
	WHERE 1=1
		AND MSISDN IS NOT NULL
		AND DIRECTION = 'OUT'
		AND REGEXP_SIMILAR(MSISDN, '55[1-9]{2}9[0-9]{8}$') = 1
		OR REGEXP_SIMILAR(MSISDN, '[1-9]{2}9[0-9]{8}$') = 1
);
SELECT TOP 10 * FROM U_INT_ATACADO.VW_LNHA_SEG_NAT;

SET QUERY_BAND = 'name=INT_ROAMING;' FOR SESSION;
--DROP TABLE U_INT_ATACADO.PRQE_RMNG_OUT_DCH;
CREATE TABLE U_INT_ATACADO.PRQE_RMNG_OUT_DCH AS(
	SELECT
		* 
	FROM U_INT_ATACADO.VW_LNHA_SEG_INT
	
	UNION 
	
	SELECT
		* 
	FROM U_INT_ATACADO.VW_LNHA_SEG_NAT
) WITH DATA PRIMARY INDEX(MSISDN, ANO, MES);

SET QUERY_BAND = 'name=INT_ROAMING;' FOR SESSION;
DROP TABLE U_INT_ATACADO.PRQE_RMNG_OUT_FINAL;
CREATE TABLE U_INT_ATACADO.PRQE_RMNG_OUT_FINAL AS (
	SELECT
	    A.IMSI AS IMSI,
	    A.MSISDN AS NR_TLFN,
	    B.DS_PRDT AS SEGMENTO,
	    B.ID_PSSA AS ID_PSSA,
	    B.ID_LNHA AS ID_LNHA,
	    B.ID_PLNO AS ID_PLNO,
	    YEAR(B.DT_FOTO_LNHA) AS ANO,
	    MONTH(B.DT_FOTO_LNHA) AS MES,
	    --B.ID_CNTA AS ID_CNTA,
	    --B.CD_CNTA AS CD_CNTA,
	    --B.DT_PRMR_ATVC_LNHA AS DT_PRMR_ATVC_LNHA,
	    CASE
	        WHEN B.DS_MODL_ORIG NOT LIKE ALL
	            (
	                '%A%','%B%','%C%','%D%','%E%','%F%','%G%','%H%','%I%','%J%','%K%',
	                '%L%','%M%','%N%','%O%','%P%','%Q%','%R%','%S%','%T%','%U%','%V%',
	                '%W%','%X%','%Y%','%Z%','%#%','%/%','%@%','%\%','%-%','%.%','% %','%+%'
	            )
	            THEN Cast(B.DS_MODL_ORIG AS DECIMAL(8)) ELSE 0
	    END AS NR_TAC,
	    C.DS_PLNO AS PLANO
	FROM U_INT_ATACADO.PRQE_RMNG_OUT_DCH A
	LEFT JOIN P_VIEDB.VW_FAT_PRQE_LNHA_DSPT B
		ON A.MSISDN = B.NR_TLFN
			AND A.ANO = YEAR(B.DT_FOTO_LNHA)
			AND A.MES = MONTH(B.DT_FOTO_LNHA)
			AND A.MSISDN IS NOT NULL
	LEFT JOIN P_VIEDB.VW_DIM_PLNO C
		ON B.ID_PLNO = C.ID_PLNO
	WHERE 1=1
	    AND B.FL_PRQE_OFCL = 1
	QUALIFY ROW_NUMBER() OVER (PARTITION BY NR_TLFN, ANO, MES ORDER BY B.DT_FOTO_LNHA DESC) = 1
) WITH DATA PRIMARY INDEX (IMSI, NR_TLFN);
SELECT TOP 10 * FROM U_INT_ATACADO.PRQE_RMNG_OUT_FINAL;

SELECT
	A.IMSI,
	A.MSISDN,
	YEAR(A.DATE_CALL),
	MONTH(A.DATE_CALL),
	B.NR_TLFN,
	B.SEGMENTO
FROM U_INT_ATACADO.FCT_RMNG_INT A
LEFT JOIN U_INT_ATACADO.PRQE_RMNG_OUT_FINAL B
ON 
	A.IMSI = B.IMSI
	AND YEAR(A.DATE_CALL) = B.ANO
	AND MONTH(A.DATE_CALL) = B.MES

WHERE 1=1
	AND A.DATE_CALL > '2026-01-01'
	AND DIRECTION = 'OUT'
	AND LEFT(CAST(B.NR_TLFN AS VARCHAR(11)), 2) IS NULL
;

SELECT * FROM P_VIEDB.VW_FAT_PRQE_LNHA_DSPT
WHERE
	DT_FOTO_LNHA >= '2026-01-01'
	AND NR_TLFN = 99991171240
	AND (FL_PRQE_OFCL = 1 OR DT_CHRN = '1900-01-01')
ORDER BY DT_FOTO_LNHA DESC
;

--RESUMOS PARA FATURAMENTO CDG (AJUSTAR)
--ESSAS VIEWS SERVEM PARA ALIMENTAR O DASHBOARD DE PROVISÃO APENAS
DROP VIEW U_INT_ATACADO.VW_RSM_CDG_INT;
CREATE VIEW U_INT_ATACADO.VW_RSM_CDG_INT AS (
	SELECT
		YEAR(A.DATE_CALL) AS ANO,
		MONTH(A.DATE_CALL) AS MES,
		CASE 
			WHEN LEFT(CAST(B.NR_TLFN AS VARCHAR(11)), 2) IS NULL
				THEN 'NI'
			ELSE LEFT(CAST(B.NR_TLFN AS VARCHAR(11)), 2)
		END AS CN,
		A.CALL_TYPE,
		A.PMN_TADIG_CODE,
		C.PMN_COUNTRY,
		C.PMN_NAME,
		C.PMN_TYPE,
		REGEXP_SIMILAR(A.MSISDN, '55[1-9]{2}9[0-9]{8}$') AS REGEX,
		CASE 
			WHEN COALESCE(B.SEGMENTO, B.PLANO) IS NULL
				THEN 'NI'
			ELSE COALESCE(B.SEGMENTO, B.PLANO)
		END AS SEGMENTO,
		SUM(A.SETTLEMENT_GROSS_CHARGE_USD) AS CUSTO_USD,
		COUNT(DISTINCT A.IMSI) AS IMSI_COUNT
	FROM U_INT_ATACADO.FCT_RMNG_INT A
	
	LEFT JOIN U_INT_ATACADO.PRQE_RMNG_OUT_FINAL B
	ON 
		A.IMSI = B.IMSI
		AND YEAR(A.DATE_CALL) = B.ANO
		AND MONTH(A.DATE_CALL) = B.MES
		
	LEFT JOIN U_INT_ATACADO.DM_OPERATORS C
		ON A.PMN_TADIG_CODE = C.PMN_TADIG_CODE
		
	WHERE 1=1
		AND DATE_CALL >= '2025-01-01'
		AND DIRECTION = 'OUT'
	GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
);
SELECT * FROM U_INT_ATACADO.VW_RSM_CDG_INT;

SELECT DISTINCT SEGMENTO, PLANO FROM U_INT_ATACADO.PRQE_RMNG_OUT_FINAL;

--IMSIs Unicos Mensal
DROP VIEW U_INT_ATACADO.VW_USRS_INT;
CREATE VIEW U_INT_ATACADO.VW_USRS_INT AS(
	SELECT
		YEAR(DATE_CALL) AS ANO,
		MONTH(DATE_CALL) AS MES,
		DIRECTION,
		PMN_TADIG_CODE,
		COUNT(DISTINCT IMSI) AS IMSI_COUNT
	FROM U_INT_ATACADO.FCT_RMNG_INT
	WHERE 1=1
		AND DATE_CALL >= '2025-01-01'
	GROUP BY 1,2,3,4
);
SELECT * FROM U_INT_ATACADO.VW_USRS_INT WHERE DIRECTION='INB' ORDER BY 5 DESC;


-- DIMENSAO OPERADORAS
DROP TABLE DM_OPERATORS;
CREATE VOLATILE TABLE DM_OPERATORS (
	PMN_TADIG_CODE VARCHAR(255),
	PMN_COUNTRY VARCHAR(255),
	PMN_NAME VARCHAR(255),
	PMN_TYPE VARCHAR(255),
	HUB_MEMBER VARCHAR(255),
	PMN_GROUP_OWNER VARCHAR(255),
	PMN_COUNTRY_ISO VARCHAR(255),
	PMN_COUNTRY_ISO_ALPHA_2 VARCHAR(255),
	PMN_COUNTRY_ISO_ALPHA_3 VARCHAR(255),
	MCC VARCHAR(255),
	MNC VARCHAR(255),
	MCCMNC VARCHAR(255)
) PRIMARY INDEX (PMN_TADIG_CODE) ON COMMIT PRESERVE ROWS;

DROP TABLE U_INT_ATACADO.DM_OPERATORS;
CREATE TABLE U_INT_ATACADO.DM_OPERATORS (
	PMN_TADIG_CODE CHAR(5),
	PMN_COUNTRY VARCHAR(125),
	PMN_NAME VARCHAR(75),
	PMN_TYPE VARCHAR(50),
	HUB_MEMBER CHAR(1),
	PMN_GROUP_OWNER CHAR(5),
	PMN_COUNTRY_ISO VARCHAR(125),
	PMN_COUNTRY_ISO_ALPHA_2 CHAR(2),
	PMN_COUNTRY_ISO_ALPHA_3 CHAR(3),
	MCC VARCHAR(3),
	MNC VARCHAR(3),
	MCCMNC VARCHAR(6)
)PRIMARY INDEX (PMN_TADIG_CODE);

INSERT INTO U_INT_ATACADO.DM_OPERATORS
	SELECT 
		CAST(PMN_TADIG_CODE AS CHAR(5)),
		CAST(PMN_COUNTRY AS VARCHAR(125)),
		CAST(PMN_NAME AS VARCHAR(75)),
		CAST(PMN_TYPE AS VARCHAR(50)),
		CAST(HUB_MEMBER AS CHAR(1)),
		CAST(PMN_GROUP_OWNER AS CHAR(5)),
		CAST(PMN_COUNTRY_ISO AS VARCHAR(125)),
		CAST(PMN_COUNTRY_ISO_ALPHA_2 AS CHAR(2)),
		CAST(PMN_COUNTRY_ISO_ALPHA_3 AS CHAR(3)),
		CAST(MCC AS VARCHAR(3)),
		CAST(MNC AS VARCHAR(3)),
		CAST(MCCMNC AS VARCHAR(6))
	FROM DM_OPERATORS;

SELECT * FROM U_INT_ATACADO.DM_OPERATORS;


SELECT TOP 10 * FROM U_INT_ATACADO.PRQE_RMNG_OUT_FINAL;
SELECT COUNT(*) FROM U_INT_ATACADO.PRQE_RMNG_OUT_FINAL;
SELECT COUNT(DISTINCT IMSI), COUNT(IMSI), ANO, MES FROM U_INT_ATACADO.PRQE_RMNG_OUT_FINAL GROUP BY 3,4;