-- TABELA FINAL - ROAMING NACIONAL

SET QUERY_BAND = 'name=INT_ROAMING;' FOR SESSION;

DROP TABLE U_INT_ATACADO.FCT_RMNG_NAT;
CREATE MULTISET TABLE U_INT_ATACADO.FCT_RMNG_NAT, FALLBACK,
	NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
	MAP = TD_MAP1
(
	-- Datas
	TAP_FILE_CURRENT_PROCESSING_DATE DATE NOT NULL, -- Data em que o TAP foi processado pela DCH. UTC-0
  	DATE_CALL DATE NOT NULL, -- Data em que a chamada ocorreu. UTC-0

  	-- Dimensões e chaves de negócio
  	DIRECTION CHAR(3) NOT NULL, -- INB = INBOUND / OUT = OUTBOUND
  	PMN_TADIG_CODE CHAR(5) NOT NULL, -- Código da Operadora -> XXXXX Ex.: BRATA
  	CALL_TYPE CHAR(6) NOT NULL, -- MOC/MTC/SMS-MO/SMS-MT/GPRS/SS
  	IMSI VARCHAR(15) NOT NULL CHECK (IMSI BETWEEN '000000000000000' AND '999999999999999'),
  	MSISDN VARCHAR(20), -- Padrão internacional: 55219XXXXXXXX. Nem sempre vem bem formatado no TAP
  	DEVICE_TAC_CODE VARCHAR(20), -- Padrão: XXXXXXXX. Nem sempre vem bem formatado no TAP
  	APN_NETWORK VARCHAR(255), -- APN utilizada pelo aparelho em chamadas GPRS
  	
  	-- Métricas de uso
  	NUMBER_OF_EVENTS INTEGER CHECK(NUMBER_OF_EVENTS >= 0),
  	CHARGED_SMS SMALLINT CHECK(CHARGED_SMS >= 0),
  	CHARGED_MINUTES DECIMAL(15,5) CHECK(CHARGED_MINUTES >= 0),
  	CHARGED_MEGABYTES  DECIMAL(15,5) CHECK(CHARGED_MEGABYTES  >= 0),
  	
  	-- Métricas financeiras
  	SETTLEMENT_GROSS_CHARGE_BRL DECIMAL(15,5) CHECK(SETTLEMENT_GROSS_CHARGE_BRL >= 0),
  	
  	-- Auditoria
  	SOURCE_FILE_NAME VARCHAR(255), -- Arquivo de origem da informação
  	SOURCE_SYSTEM VARCHAR(255), -- Sistema de Origem (DCH, BO, etc)
  	JOB_NAME VARCHAR(255), -- Job que realizou a carga
  	ETL_BATCH_ID VARCHAR(50), -- ID de Batch
  	ROW_CREATE_TS TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP, -- TIMESTAMP em que a informação foi carregada no Teradata
	ROW_CREATE_USER VARCHAR(128) DEFAULT USER -- Usuário que carregou a informação
)
PRIMARY INDEX (DATE_CALL, DIRECTION, PMN_TADIG_CODE)
PARTITION BY RANGE_N(DATE_CALL BETWEEN 	DATE '2024-01-01'
                               AND 		DATE '2199-12-31'
                               EACH 	INTERVAL '1' MONTH);
                               
-- INSERIR DADOS DA STAGING PARA A TABELA FINAL
INSERT INTO U_INT_ATACADO.FCT_RMNG_NAT
	SELECT
		TAP_FILE_CURRENT_PROCESSING_DATE,
		DATE_CALL,
		DIRECTION,
		PMN_SETTLEMENT_TADIG_CODE,
		CALL_TYPE,
		IMSI,
		MSISDN,
		DEVICE_TAC_CODE,
		APN_NETWORK,
		NUMBER_OF_CALLS,
		CHARGED_SMS,
		CHARGED_MINUTES,
		CHARGED_MB,
		SETTLEMENT_GROSS_CHARGE_USD,
		SOURCE_FILE_NAME,
	  	SOURCE_SYSTEM,
	  	JOB_NAME,
	  	ETL_BATCH_ID,
	  	ROW_CREATE_TS,
		ROW_CREATE_USER
	FROM DL_ROAMING.STAGING_NAT_INB_TRAFFIC_HIST;
	
INSERT INTO U_INT_ATACADO.FCT_RMNG_NAT
	SELECT
		TAP_FILE_CURRENT_PROCESSING_DATE,
		DATE_CALL,
		DIRECTION,
		PMN_SETTLEMENT_TADIG_CODE,
		CALL_TYPE,
		IMSI,
		MSISDN,
		DEVICE_TAC_CODE,
		APN_NETWORK,
		NUMBER_OF_CALLS,
		CHARGED_SMS,
		CHARGED_MINUTES,
		CHARGED_MB,
		SETTLEMENT_GROSS_CHARGE_USD,
		SOURCE_FILE_NAME,
	  	SOURCE_SYSTEM,
	  	JOB_NAME,
	  	ETL_BATCH_ID,
	  	ROW_CREATE_TS,
		ROW_CREATE_USER
	FROM DL_ROAMING.STAGING_NAT_OUT_TRAFFIC_HIST;
	

-- TRAFEGO DIARIO NACIONAL - SEM SEPARACAO M2M
DROP VIEW U_INT_ATACADO.VW_DLY_TRFC_NAT;
CREATE VIEW U_INT_ATACADO.VW_DLY_TRFC_NAT AS
	SELECT
		DATE_CALL,
		CALL_TYPE,
		PMN_TADIG_CODE,
		DIRECTION,
		COUNT(DISTINCT IMSI) AS IMSI,
		MAX(
			LEFT(
				CAST(IMSI AS CHAR(15)), 5
				)
			) AS MCCMNC,
		SUM(CHARGED_MEGABYTES) AS CHARGED_MEGABYTES,
		SUM(CHARGED_MEGABYTES)/1024 AS CHARGED_GIGABYTES,
		SUM(CHARGED_MEGABYTES)/1024**2 AS CHARGED_TERABYTES,
		SUM(CHARGED_MINUTES) AS CHARGED_MINUTES,
		SUM(CHARGED_MINUTES)/60 AS CHARGED_HOURS,
		SUM(CHARGED_SMS) AS CHARGED_SMS,
		SUM(SETTLEMENT_GROSS_CHARGE_BRL) AS SETTLEMENT_GROSS_CHARGE_BRL
	FROM U_INT_ATACADO.FCT_RMNG_NAT
	GROUP BY 1, 2, 3, 4;

SELECT * FROM U_INT_ATACADO.VW_DLY_TRFC_NAT;