SELECT
	A.IMSI,
	A.MSISDN,
	YEAR(A.DATE_CALL),
	MONTH(A.DATE_CALL),
	B.NR_TLFN,
	B.SEGMENTO
FROM U_INT_ATACADO.FCT_RMNG_INT A
LEFT JOIN U_INT_ATACADO.PRQE_RMNG_OUT_FINAL B
ON 
	A.IMSI = B.IMSI
	AND YEAR(A.DATE_CALL) = B.ANO
	AND MONTH(A.DATE_CALL) = B.MES

WHERE 1=1
	AND A.DATE_CALL > '2026-01-01'
	AND DIRECTION = 'OUT'
	AND LEFT(CAST(B.NR_TLFN AS VARCHAR(11)), 2) IS NULL
;

SELECT * FROM P_VIEDB.VW_FAT_PRQE_LNHA_DSPT
WHERE
	DT_FOTO_LNHA >= '2026-01-01'
	AND NR_TLFN = 99991171240
	AND (FL_PRQE_OFCL = 1 OR DT_CHRN = '1900-01-01')
ORDER BY DT_FOTO_LNHA DESC
;

--RESUMOS PARA FATURAMENTO CDG (AJUSTAR)
--ESSAS VIEWS SERVEM PARA ALIMENTAR O DASHBOARD DE PROVIS�O APENAS
DROP VIEW U_INT_ATACADO.VW_RSM_CDG_INT;
CREATE VIEW U_INT_ATACADO.VW_RSM_CDG_INT AS (
	SELECT
		YEAR(A.DATE_CALL) AS ANO,
		MONTH(A.DATE_CALL) AS MES,
		CASE 
			WHEN LEFT(CAST(B.NR_TLFN AS VARCHAR(11)), 2) IS NULL
				THEN 'NI'
			ELSE LEFT(CAST(B.NR_TLFN AS VARCHAR(11)), 2)
		END AS CN,
		A.CALL_TYPE,
		A.PMN_TADIG_CODE,
		C.PMN_COUNTRY,
		C.PMN_NAME,
		C.PMN_TYPE,
		REGEXP_SIMILAR(A.MSISDN, '55[1-9]{2}9[0-9]{8}$') AS REGEX,
		CASE 
			WHEN COALESCE(B.SEGMENTO, B.PLANO) IS NULL
				THEN 'NI'
			ELSE COALESCE(B.SEGMENTO, B.PLANO)
		END AS SEGMENTO,
		SUM(A.SETTLEMENT_GROSS_CHARGE_USD) AS CUSTO_USD,
		COUNT(DISTINCT A.IMSI) AS IMSI_COUNT
	FROM U_INT_ATACADO.FCT_RMNG_INT A
	
	LEFT JOIN U_INT_ATACADO.PRQE_RMNG_OUT_FINAL B
	ON 
		A.IMSI = B.IMSI
		AND YEAR(A.DATE_CALL) = B.ANO
		AND MONTH(A.DATE_CALL) = B.MES
		
	LEFT JOIN U_INT_ATACADO.DM_OPERATORS C
		ON A.PMN_TADIG_CODE = C.PMN_TADIG_CODE
		
	WHERE 1=1
		AND DATE_CALL >= '2025-01-01'
		AND DIRECTION = 'OUT'
	GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
);
SELECT * FROM U_INT_ATACADO.VW_RSM_CDG_INT;

SELECT DISTINCT SEGMENTO, PLANO FROM U_INT_ATACADO.PRQE_RMNG_OUT_FINAL;

--IMSIs Unicos Mensal
DROP VIEW U_INT_ATACADO.VW_USRS_INT;
CREATE VIEW U_INT_ATACADO.VW_USRS_INT AS(
	SELECT
		YEAR(DATE_CALL) AS ANO,
		MONTH(DATE_CALL) AS MES,
		DIRECTION,
		PMN_TADIG_CODE,
		COUNT(DISTINCT IMSI) AS IMSI_COUNT
	FROM U_INT_ATACADO.FCT_RMNG_INT
	WHERE 1=1
		AND DATE_CALL >= '2025-01-01'
	GROUP BY 1,2,3,4
);
SELECT * FROM U_INT_ATACADO.VW_USRS_INT WHERE DIRECTION='INB' ORDER BY 5 DESC;


-- DIMENSAO OPERADORAS
DROP TABLE DM_OPERATORS;
CREATE VOLATILE TABLE DM_OPERATORS (
	PMN_TADIG_CODE VARCHAR(255),
	PMN_COUNTRY VARCHAR(255),
	PMN_NAME VARCHAR(255),
	PMN_TYPE VARCHAR(255),
	HUB_MEMBER VARCHAR(255),
	PMN_GROUP_OWNER VARCHAR(255),
	PMN_COUNTRY_ISO VARCHAR(255),
	PMN_COUNTRY_ISO_ALPHA_2 VARCHAR(255),
	PMN_COUNTRY_ISO_ALPHA_3 VARCHAR(255),
	MCC VARCHAR(255),
	MNC VARCHAR(255),
	MCCMNC VARCHAR(255)
) PRIMARY INDEX (PMN_TADIG_CODE) ON COMMIT PRESERVE ROWS;

DROP TABLE U_INT_ATACADO.DM_OPERATORS;
CREATE TABLE U_INT_ATACADO.DM_OPERATORS (
	PMN_TADIG_CODE CHAR(5),
	PMN_COUNTRY VARCHAR(125),
	PMN_NAME VARCHAR(75),
	PMN_TYPE VARCHAR(50),
	HUB_MEMBER CHAR(1),
	PMN_GROUP_OWNER CHAR(5),
	PMN_COUNTRY_ISO VARCHAR(125),
	PMN_COUNTRY_ISO_ALPHA_2 CHAR(2),
	PMN_COUNTRY_ISO_ALPHA_3 CHAR(3),
	MCC VARCHAR(3),
	MNC VARCHAR(3),
	MCCMNC VARCHAR(6)
)PRIMARY INDEX (PMN_TADIG_CODE);

INSERT INTO U_INT_ATACADO.DM_OPERATORS
	SELECT 
		CAST(PMN_TADIG_CODE AS CHAR(5)),
		CAST(PMN_COUNTRY AS VARCHAR(125)),
		CAST(PMN_NAME AS VARCHAR(75)),
		CAST(PMN_TYPE AS VARCHAR(50)),
		CAST(HUB_MEMBER AS CHAR(1)),
		CAST(PMN_GROUP_OWNER AS CHAR(5)),
		CAST(PMN_COUNTRY_ISO AS VARCHAR(125)),
		CAST(PMN_COUNTRY_ISO_ALPHA_2 AS CHAR(2)),
		CAST(PMN_COUNTRY_ISO_ALPHA_3 AS CHAR(3)),
		CAST(MCC AS VARCHAR(3)),
		CAST(MNC AS VARCHAR(3)),
		CAST(MCCMNC AS VARCHAR(6))
	FROM DM_OPERATORS;

SELECT * FROM U_INT_ATACADO.DM_OPERATORS;


SELECT TOP 10 * FROM U_INT_ATACADO.PRQE_RMNG_OUT_FINAL;
SELECT COUNT(*) FROM U_INT_ATACADO.PRQE_RMNG_OUT_FINAL;
SELECT COUNT(DISTINCT IMSI), COUNT(IMSI), ANO, MES FROM U_INT_ATACADO.PRQE_RMNG_OUT_FINAL GROUP BY 3,4;